[package]
name = "ggez_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"

# ggez and winit are slow and loading images otherwise
[profile.dev.package."*"]
opt-level = 1
